### PR TITLE
Nuke.js updated

### LINKED ISSUE #7: Nuke argument to send less than 20 pings
For example:
`xd)nuke @someone 10`

This will send only 10 pings instead of the usual 20+.

### PR DESCRIPTION
**Pull request by MomentarilyDisabled**
Added second argument for number of pings

### CODE REVIEW

**Review by Colind8 — CHANGES_REQUESTED** [review]
Make it so entering a number over 20 just makes it 20.

**Comment by MomentarilyDisabled** [comment]
Made it so any number over 20 just pings 20

**Review by Colind8 — APPROVED** [review]

**Review by Colind8 — CHANGES_REQUESTED** [review]
Two more things, on the for loop, subtract 1 from pn so that the final "as been nuked" message brings the counted pings to 20 instead of 21.

Also set pn to 2 if pn is less than 2

**Comment by MomentarilyDisabled** [comment]
> Two more things, on the for loop, subtract 1 from pn so that the final "as been nuked" message brings the counted pings to 20 instead of 21.
> 
> Also set pn to 2 if pn is less than 2

Done!

**Review by Colind8 — APPROVED** [review]

**Pull request merged**
